name: Main workflow

on:
  push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: unit tests
      - run: make test